-- Tipos de documento
INSERT INTO new_idiomas_document_type (id, name) VALUES
(1, 'DNI'),
(2, 'Carnet de Extranjeria'),
(3, 'Pasaporte'),
(4, 'Tarjeta de Residencia');

-- Países
INSERT INTO countries (id, name) VALUES
(9101, 'Argelia'),
(9102, 'Argentina'),
(9103, 'Brasil'),
(9104, 'Chile'),
(9105, 'Colombia'),
(9106, 'Ecuador'),
(9233, 'Peru'),
(9234, 'Bolivia'),
(9300, 'México'),
(9508, 'República De Fiyi');

-- Roles de usuario
INSERT INTO new_idiomas_role (id, name) VALUES
(1, 'Coordinador'),
(2, 'Docente'),
(3, 'Programador'),
(4, 'Asesor'),
(5, 'Asistente'),
(6, 'Estudiante'),
(7, 'Consultor de certificados');

INSERT INTO new_idiomas_teacher_state (id, name) VALUES
(1, 'Activo'),
(2, 'Inactivo');

INSERT INTO new_idiomas_student_state (id, name) VALUES
(1, 'Activo'),
(2, 'Inactivo');

INSERT INTO new_idiomas_postgraduate_permanency (id, name) VALUES
(1, 'Reserva de Ingreso'),
(2, 'Egresado'),
(3, 'Activo'),
(4, 'Expulsado / Separado'),
(5, 'Inactivo'),
(6, 'Reserva de Matricula'),
(7, 'Anulacion de Ingreso'),
(8, 'Abandono'),
(9, 'Concluido'),
(10, 'Anulacion derecho de matricula'),
(11, 'Estancia Academica'),
(12, 'Anulacion de Oficio'),
(13, 'Sepacion Automatica');

INSERT INTO new_idiomas_faculty (id, name) VALUES
(1, 'Medicina'),
(2, 'Derecho y ciencias politicas'),
(3, 'Letras y ciencias humanas'),
(4, 'Farmacia y bioquimica'),
(5, 'Odontologia'),
(6, 'Educacion'),
(7, 'Quimica e ingenieria quimica'),
(8, 'Medicina veterinaria'),
(9, 'Ciencias administrativas'),
(10, 'Ciencias biologicas'),
(11, 'Ciencias contables'),
(12, 'Ciencias economicas'),
(13, 'Ciencias fisicas'),
(14, 'Ciencias matematicas'),
(15, 'Ciencias sociales'),
(16, 'Ingenieria geologica, minera, metalurgica y geografica'),
(17, 'Ingenieria industrial'),
(18, 'Psicologia'),
(19, 'Ingenieria electronica y electrica'),
(20, 'Ingenieria de sistemas e informatica');

INSERT INTO new_idiomas_postgraduate_program (faculty_id, program_id, name) VALUES
(201, 'Segunda Especialidad en Animales de Compañía'),
(201, 'Segunda Especialidad en Computación e Informática'),
(201, 'Segunda Especialidad en Derecho y Ciencia Política'),
(201, 'Segunda Especialidad en Educación'),
(201, 'Segunda Especialidad en Farmacia y Bioquímica'),
(201, 'Segunda Especialidad en Lingüística Hispánica'),
(201, 'Segunda Especialidad en Medicina Humana'),
(201, 'Segunda Especialidad en Odontología'),
(201, 'Segunda Especialidad en Psicología'),
(202, 'Segunda Especialidad en Avicultura'),
(202, 'Segunda Especialidad en Enfermería'),
(202, 'Segunda Especialidad en Estrategias de Evaluación'),
(202, 'Segunda Especialidad en Productos Sanitarios, Materiales'),
(202, 'Segunda Especialidad Profesional en Periodoncia'),
(203, 'Segunda Especialidad en Epidemiología de Campo'),
(203, 'Segunda Especialidad en Epidemiología y Economía de la Salud'),
(203, 'Segunda Especialidad en Intervención Temprana en Niños'),
(203, 'Segunda Especialidad en Políticas y Regulación Farmacéutica'),
(203, 'Segunda Especialidad Profesional en Endodoncia'),
(204, 'Programa de Residentado en Clínica de Animales Menores'),
(204, 'Programa de Segunda Especialidad para Nutricionistas'),
(205, 'Programa de Residentado en Medicina y Producción Animal'),
(205, 'Programa de Segunda Especialidad para Obstetras'),
(206, 'Programa de Residentado en Clínica y Patología Avícola'),
(206, 'Segunda Especialidad Profesional en Ortodoncia y Odontología'),
(207, 'Segunda Especialidad en Porcicultura'),
(207, 'Segunda Especialidad Profesional en Odontopediatría'),
(208, 'Segunda Especialidad Profesional en Rehabilitación Oral'),
(209, 'Segunda Especialidad Profesional en Cirugía Bucal y Maxilofacial'),
(210, 'Segunda Especialidad Profesional en Odontología Forense'),
(301, 'Diplomatura de Especialización en Normas Internacionales'),
(301, 'Diplomatura en Arqueometría'),
(301, 'Diplomatura en Atención Farmacéutica'),
(301, 'Diplomatura en Cirugía Periodontal'),
(301, 'Diplomatura en Especialización en Auditoría y Seguimiento'),
(301, 'Diplomatura en Formación de Formadores en Salud Integral'),
(301, 'Diplomatura en Gestión Ambiental para el Desarrollo Sostenible'),
(301, 'Diplomatura en Gestión de la Biodiversidad'),
(301, 'Diplomatura en Gestión de la Innovación y Emprendimiento'),
(301, 'Diplomatura en Ingeniería Electrónica Aplicada a Empresas'),
(301, 'Diplomatura en Programa de Estudios Sobre Poder y Gobernanza'),
(301, 'Diplomatura en Psicopedagogía'),
(301, 'Diplomatura Internacional en Seguridad Integral'),
(302, 'Diplomatura en Análisis Político'),
(302, 'Diplomatura en Gerencia de Proyectos en Tecnología'),
(302, 'Diplomatura en Gerenciamiento de los Energéticos y Recursos Naturales'),
(302, 'Diplomatura en Gestión de Procesos Electorales'),
(302, 'Diplomatura en Gestión en Clínicas Veterinarias'),
(302, 'Diplomatura en Gestión y Aprovechamiento de Plantas Medicinales'),
(302, 'Diplomatura en Gestión y Supervisión del Sector Eléctrico'),
(302, 'Diplomatura en Implantología Oral'),
(302, 'Diplomatura en Museología'),
(302, 'Diplomatura en Psicoterapia por el Arte'),
(302, 'Diplomatura Internacional de Control Interno Empresarial'),
(303, 'Diplomado en Gestión y Políticas Públicas'),
(303, 'Diplomatura de Especialización en Tributación y Planificación Fiscal'),
(303, 'Diplomatura en Gestión de Ciencia, Tecnología y Sociedad'),
(303, 'Diplomatura en Gestión de Recursos Humanos'),
(303, 'Diplomatura en Odontología del Niño y Adolescente'),
(304, 'Diplomatura de Especialización en Tributación y Planificación Fiscal'),
(304, 'Diplomatura en Antropología Forense y Derecho Humano'),
(304, 'Diplomatura en Asuntos Regulatorios Farmacéuticos'),
(304, 'Diplomatura en Auditoría Médica'),
(304, 'Diplomatura en Consejería en Adicciones'),
(304, 'Diplomatura en Gestión Pública'),
(304, 'Diplomatura en Gestión Pública y Gobierno Electrónico'),
(304, 'Diplomatura en Ingeniería Clínica'),
(304, 'Diplomatura en Manejo de Fauna Silvestre'),
(304, 'Diplomatura en Técnicas Ortodónticas Fijas'),
(305, 'Diplomatura en Ciberseguridad'),
(305, 'Diplomatura en Conservación Preventiva de Bienes Culturales'),
(305, 'Diplomatura en Dificultades de Aprendizaje en Lectura y Escritura'),
(305, 'Diplomatura en Estética Restauradora'),
(305, 'Diplomatura en Ética y Deontología en Salud'),
(305, 'Diplomatura en Evaluación Sanitaria de Productos Farmacéuticos'),
(305, 'Diplomatura en Puesta en valor de Bienes Patrimoniales'),
(306, 'Diplomatura de Especialización en Finanzas y Gestión Empresarial'),
(306, 'Diplomatura en Aseguramiento y Auditorías de Sistemas de Salud'),
(306, 'Diplomatura en Desarrollo Integral y Prevención de Adicciones'),
(306, 'Diplomatura en Endodoncia Clínica'),
(306, 'Diplomatura en Neurociencias'),
(306, 'Diplomatura en Políticas Públicas y Gestión en Salud'),
(306, 'Diplomatura en Revitalización Lingüística y Cultural'),
(307, 'Diplomatura en Gestión del Riesgo y Adaptación al Cambio Climático'),
(307, 'Diplomatura en Prótesis Fija'),
(307, 'Diplomatura en Psicología Forense'),
(307, 'Diplomatura Virtual en Gestión de la Cadena de Suministro'),
(307, 'Programa de Epidemiología de Campo IV Etapa'),
(308, 'Diplomatura de Especialización en Auditoría Financiera'),
(308, 'Diplomatura en Acompañamiento y Evaluación de la Terapia Psicológica'),
(308, 'Diplomatura en Cirugía Bucal'),
(308, 'Diplomatura en Evaluación Psicológica Forense'),
(308, 'Diplomatura en Evaluación y Registro Sanitario de Productos Farmacéuticos'),
(308, 'Diplomatura en Toxicología Forense'),
(309, 'Diplomado en Cirugía Bucal'),
(309, 'Diplomatura en Manejo Avícola'),
(309, 'Diplomatura en Peritaje Psicológico'),
(309, 'Diplomatura en Preparación Física'),
(309, 'Diplomatura en Promoción de la Salud'),
(310, 'Diplomatura en Diseños Cualitativos y Experimentales'),
(310, 'Diplomatura en Gestión de Proyectos Sociales con Enfoque en Desarrollo Comunitario'),
(310, 'Diplomatura en Producción Avícola'),
(310, 'Diplomatura en Terapias Alternativas'),
(311, 'Diplomado en Metodologías Activas para el Desarrollo Educativo'),
(311, 'Diplomatura en Dirección Estratégica de Costos'),
(311, 'Diplomatura en Inspección e Inocuidad de Carnes'),
(311, 'Diplomatura Interdisciplinaria en Políticas de Cuidado de la Salud'),
(312, 'Diplomatura de Especialización en Gestión y Procedimientos en Salud'),
(312, 'Diplomatura en Clínica y Cirugía en Bovinos'),
(312, 'Diplomatura en Historia del Pensamiento Educativo'),
(313, 'Diplomatura en Ciencias de la Nutrición'),
(314, 'Diplomatura en Compliance Penal y la Pericia Contable'),
(314, 'Diplomatura en Epidemiología Aplicada a la Gestión de Salud'),
(314, 'Diplomatura en Participación Política y Democracia'),
(314, 'Diplomatura en Principios de Anestesia Veterinaria'),
(315, 'Diplomatura de Clínica y Cirugía en Equinos'),
(315, 'Diplomatura en Epidemiología Aplicada a la Gestión en Salud'),
(316, 'Diplomatura en Manejo Integral de la TBC-VIH/Sida en Poblaciones Vulnerables'),
(316, 'Especialización Internacional en Contabilidad Gerencial'),
(317, 'Diplomatura en Atención Integral en Salud a Víctimas de Violencia'),
(317, 'Programa de Alta Especialización en Formación de Recursos Humanos'),
(318, 'Diplomatura en Genética y Embriogenia Humana'),
(318, 'Diplomatura en Normas Internacionales de Contabilidad Financiera'),
(319, 'Diplomatura en Atención Integral con Enfoque en Salud Mental'),
(320, 'Diplomatura en Salud Materno Infantil'),
(321, 'Diplomatura de Gestión de la Calidad en Salud'),
(322, 'Diplomatura en Asesoría de Tesis'),
(325, 'Diplomatura en Especialización en Salud Digital y Telemedicina'),
(326, 'Diplomatura en Endocrinología en Ginecología y Obstetricia'),
(327, 'Diplomatura en Manejo Integral del Dolor Crónico'),
(328, 'Diplomado en Gestión de Redes Integradas de Salud'),
(329, 'Diplomatura en Cuidados Paliativos'),
(401, 'Maestría en Administración'),
(401, 'Maestría en Botánica Tropical'),
(401, 'Maestría en Bromatología'),
(401, 'Maestría en Contabilidad'),
(401, 'Maestría en Derecho'),
(401, 'Maestría en Economía'),
(401, 'Maestría en Educación'),
(401, 'Maestría en Estomatología'),
(401, 'Maestría en Física'),
(401, 'Maestría en Fisiología'),
(401, 'Maestría en Geología'),
(401, 'Maestría en Ingeniería de Sistemas e Informática'),
(401, 'Maestría en Ingeniería Industrial'),
(401, 'Maestría en Literatura Peruana y Latinoamericana'),
(401, 'Maestría en Matemática Pura'),
(401, 'Maestría en Microelectrónica'),
(401, 'Maestría en Política Social'),
(401, 'Maestría en Producción y Reproducción Animal'),
(401, 'Maestría en Psicología'),
(401, 'Maestría en Química'),
(402, 'Maestría en Auditoría'),
(402, 'Maestría en Ciencias Veterinarias'),
(402, 'Maestría en Economía de la Salud'),
(402, 'Maestría en Educación Física'),
(402, 'Maestría en Estadística'),
(402, 'Maestría en Farmacología'),
(402, 'Maestría en Filosofía'),
(402, 'Maestría en Gestión de la Información y del Conocimiento'),
(402, 'Maestría en Gestión Estratégica de Turismo'),
(402, 'Maestría en Gestión y Tecnología Textil'),
(402, 'Maestría en Historia'),
(402, 'Maestría en Ingeniería Hidráulica'),
(402, 'Maestría en Ingeniería Metalúrgica'),
(402, 'Maestría en Ingeniería Química'),
(402, 'Maestría en Odontoestomatología de Salud Pública'),
(402, 'Maestría en Recursos Acuáticos'),
(402, 'Maestría en Salud Ocupacional'),
(402, 'Maestría en Telecomunicaciones'),
(403, 'Maestría en Arqueometría'),
(403, 'Maestría en Banca y Finanzas'),
(403, 'Maestría en Ciencias de la Gestión Económico Empresarial'),
(403, 'Maestría en Ciencias de la Religión'),
(403, 'Maestría en Computación e Informática'),
(403, 'Maestría en Dirección de Empresas Industriales y de Servicios'),
(403, 'Maestría en Dirección Estratégica de las Telecomunicaciones'),
(403, 'Maestría en Enfermería'),
(403, 'Maestría en Geografía'),
(403, 'Maestría en Gestión Pública'),
(403, 'Maestría en Lingüística'),
(403, 'Maestría en Recursos Vegetales y Terapéuticos'),
(403, 'Maestría en Salud Animal'),
(403, 'Maestría en Tecnología Agroindustrial'),
(403, 'Maestría en Zoología'),
(403, 'Maestría Profesional en Didáctica de la Comunicación'),
(403, 'Maestría Profesional en Gobierno de Tecnologías de la Información'),
(403, 'Maestría Profesional en Psicología Criminológica'),
(404, 'Maestría en Antropología'),
(404, 'Maestría en Biología Molecular'),
(404, 'Maestría en Bioquímica'),
(404, 'Maestría en Biotecnología'),
(404, 'Maestría en Ciencia Animal'),
(404, 'Maestría en Ciencias Ambientales'),
(404, 'Maestría en Comunicación Social'),
(404, 'Maestría en Gestión de Operaciones y Servicios Logísticos'),
(404, 'Maestría en Ingeniería de Tecnologías de la Información'),
(404, 'Maestría en Investigación de Operaciones y Sistemas'),
(404, 'Maestría en Política y Gestión Tributaria'),
(404, 'Maestría Profesional en Didáctica de la Matemática'),
(404, 'Maestría Profesional en Gestión de Negocios Internacionales'),
(405, 'Maestría en Arqueología Andina'),
(405, 'Maestría en Arte Peruano y Latinoamericano'),
(405, 'Maestría en Comercio Internacional y Aduanas'),
(405, 'Maestría en Genética'),
(405, 'Maestría en Gerencia en Estadística e Informática'),
(405, 'Maestría en Gestión Integrada en Seguridad, Salud y Medio Ambiente'),
(405, 'Maestría en Microbiología'),
(405, 'Maestría en Nutrición'),
(405, 'Maestría en Prospectiva Estratégica para el Desarrollo'),
(405, 'Maestría Profesional en Prevención de Riesgos Laborales'),
(406, 'Maestría en Bioestadística'),
(406, 'Maestría en Ciencia de Los Alimentos'),
(406, 'Maestría en Ecosistemas y Recursos Acuáticos'),
(406, 'Maestría en Educación Intercultural Bilingüe'),
(406, 'Maestría en Epidemiología'),
(406, 'Maestría en Finanzas Públicas'),
(406, 'Maestría en Gestión de Negocios Internacionales'),
(406, 'Maestría en Ingeniería de Minas'),
(406, 'Maestría en Sociología'),
(406, 'Maestría en Supply Chain Management'),
(407, 'Maestría en Biodiversidad y Gestión de Ecosistemas'),
(407, 'Maestría en Control Gubernamental y Gestión Pública'),
(407, 'Maestría en Dirección De Empresas'),
(407, 'Maestría en Estadística Matemática'),
(407, 'Maestría en Estudios Amazónicos'),
(407, 'Maestría en Geometalurgia'),
(407, 'Maestría en Literatura'),
(407, 'Maestría en Medicina'),
(407, 'Maestría en Toxicología'),
(408, 'Maestría en Atención Farmacéutica'),
(408, 'Maestría en Bioinformática y Ciencias Ómicas'),
(408, 'Maestría en Escritura Creativa'),
(408, 'Maestría en Geografía'),
(408, 'Maestría en Matemática Aplicada'),
(408, 'Maestría en Obstetricia'),
(408, 'Maestría en Prevención de Riesgos Laborales y Ambientales'),
(408, 'Maestría Profesional en Liderazgo y Alta Dirección'),
(409, 'Maestría en Ciencias Farmacéuticas'),
(409, 'Maestría en Ciencias Sociales y Filosofía Latinoamericana'),
(409, 'Maestría en Gerencia de Servicios de Salud'),
(409, 'Maestría en Lengua y Literatura'),
(409, 'Maestría Profesional en Tributación Internacional'),
(410, 'Maestría en Bibliotecología e Información'),
(410, 'Maestría en Género, Sexualidad y Políticas Públicas'),
(410, 'Maestría en Química Clínica'),
(410, 'Maestría en Salud Pública'),
(410, 'Maestría Profesional en Auditoría Forense y Compliance'),
(411, 'Maestría de Especialización en Contabilidad Internacional'),
(411, 'Maestría en Comunicaciones'),
(411, 'Maestría en Infectología Pediátrica'),
(411, 'Maestría en Productos Naturales y Biocomercio'),
(411, 'Maestría Internacional en Desarrollo Sustentable'),
(412, 'Maestría en Gestión del Patrimonio Cultural'),
(412, 'Maestría en Salud Reproductiva'),
(413, 'Maestría en Arqueología'),
(413, 'Maestría en Enfermedades Infecciosas y Tropicales'),
(414, 'Maestría en Bioética'),
(414, 'Maestría en Género y Desarrollo'),
(415, 'Maestría en Docencia e Investigación en Salud'),
(415, 'Maestría en Trabajo Social'),
(416, 'Maestría en Neurociencias'),
(417, 'Maestría en Políticas y Planificación en Salud'),
(418, 'Maestría en Salud Ocupacional y Ambiental'),
(419, 'Maestría en Ética en Salud y Bioética Clínica'),
(419, 'Maestría en Gestión de la Información'),
(420, 'Maestría en Salud Infantil Comunitaria'),
(421, 'Maestría en Salud Sexual y Reproductiva'),
(423, 'Maestría Profesional en Gestión en Sistemas de Emergencia'),
(424, 'Maestría en Cuidados Paliativos y Manejo del Dolor'),
(501, 'Doctorado en Ciencias Administrativas'),
(501, 'Doctorado en Ciencias Ambientales'),
(501, 'Doctorado en Ciencias Biológicas'),
(501, 'Doctorado en Ciencias Contables y Empresariales'),
(501, 'Doctorado en Ciencias Químicas'),
(501, 'Doctorado en Ciencias Sociales'),
(501, 'Doctorado en Derecho y Ciencia Política'),
(501, 'Doctorado en Economía'),
(501, 'Doctorado en Educación'),
(501, 'Doctorado en Estomatología'),
(501, 'Doctorado en Farmacia y Bioquímica'),
(501, 'Doctorado en Física'),
(501, 'Doctorado en Ingeniería de Sistemas e Informática'),
(501, 'Doctorado en Ingeniería Industrial'),
(501, 'Doctorado en Literatura Peruana y Latinoamericana'),
(501, 'Doctorado en Matemática Pura'),
(501, 'Doctorado en Medicina'),
(501, 'Doctorado en Medicina Veterinaria'),
(501, 'Doctorado en Psicología'),
(502, 'Doctorado en Ciencias de la Salud'),
(502, 'Doctorado en Ciencias Veterinarias'),
(502, 'Doctorado en Educación y Docencia Universitaria'),
(502, 'Doctorado en Estadística'),
(502, 'Doctorado en Filosofía'),
(502, 'Doctorado en Gestión de Empresas'),
(502, 'Doctorado en Gestión Económica Global'),
(502, 'Doctorado en Ingeniería Química'),
(502, 'Doctorado en Política Fiscal y Sistema Tributario'),
(503, 'Doctorado en Gerencia de Empresas'),
(503, 'Doctorado en Lingüística'),
(503, 'Doctorado en Marketing'),
(503, 'Doctorado en Neurociencias'),
(504, 'Doctorado en Enfermería'),
(504, 'Doctorado en Historia del Arte'),
(505, 'Doctorado en Comunicación, Periodismo y Medios Digitales');

-- Idiomas
INSERT INTO new_idiomas_language (id, name) VALUES
(1, 'Inglés'),
(2, 'Portugués'),
(3, 'Italiano'),
(4, 'Francés'),
(5, 'Quechua'),
(6, 'Aymara');

-- Programas
INSERT INTO new_idiomas_program (id, name) VALUES
(1, 'Regular'),
(2, 'Repaso'),
(3, 'Intensivo');

-- Niveles
INSERT INTO new_idiomas_level (id, name) VALUES
(1, 'Básico'),
(2, 'Intermedio'),
(3, 'Avanzado');

-- Días
INSERT INTO new_idiomas_day (id, name) VALUES
(1, 'Lunes'),
(2, 'Martes'),
(3, 'Miércoles'),
(4, 'Jueves'),
(5, 'Viernes'),
(6, 'Sábado'),
(7, 'Domingo');

-- Secciones
INSERT INTO new_idiomas_section (id, name) VALUES
(1, 'A'),
(2, 'B'),
(3, 'C');

-- Estados de curso
INSERT INTO new_idiomas_courses_state (id, name) VALUES
(1, 'En matrícula'),
(2, 'En curso'),
(3, 'Inhabilitado'),
(4, 'Cerrado'),
(5, 'En matrícula interna');

-- Métodos de pago
INSERT INTO new_idiomas_payment_method (id, name) VALUES
(1, 'Agentes BCP'),
(2, 'Yape'),
(3, 'Banca Móvil');

-- Estados de pago
INSERT INTO new_idiomas_payment_state (id, name) VALUES
(1, 'En revisión'),
(2, 'Aprobado'),
(3, 'Rechazado');

-- Estados de solicitud de matrícula
INSERT INTO new_idiomas_enrollment_request_state (id, name) VALUES
(1, 'Pendiente'),
(2, 'Aprobada'),
(3, 'Rechazada'),
(4, 'Rezagada');

-- Estados del estudiante en curso
INSERT INTO new_idiomas_course_student_state (id, name) VALUES
(1, 'Matriculado'),
(2, 'Alumno libre'),
(3, 'Rezagado'),
(4, 'Retirado');

-- Estados de solicitud de rezago
INSERT INTO new_idiomas_straggle_state (id, name) VALUES
(1, 'Pendiente'),
(2, 'Completada');

-- Modalidades de examen
INSERT INTO new_idiomas_exam_modality (id, name) VALUES
(1, 'Ordinario'),
(2, 'Extraordinario');

-- Estados del examen
INSERT INTO new_idiomas_exam_state (id, name) VALUES
(1, 'En Inscripción'),
(2, 'En Curso'),
(3, 'Inhabilitado'),
(4, 'Finalizado');

-- Estados del estudiante en examen
INSERT INTO new_idiomas_exam_student_state (id, name) VALUES
(1, 'Inscrito'),
(2, 'Rezagado'),
(3, 'Retirado');

-- Estados de solicitud de suficiencia
INSERT INTO new_idiomas_proficiency_request_state (id, name) VALUES
(1, 'Pendiente'),
(2, 'Aprobada'),
(3, 'Rechazada');
